const data = {
  result: [
    {
      id: 1,
      categoryId: 4,
      paymentId: 1,
      title: '커피',
      value: 5400,
      date: '7월 2일 금',
    },
    {
      id: 2,
      categoryId: 10,
      paymentId: 1,
      title: '체육관 수강 등록',
      value: 125300,
      date: '7월 4일 일',
    },
    {
      id: 3,
      categoryId: 4,
      paymentId: 1,
      title: '토마토 소스 오므라이스',
      value: 6500,
      date: '7월 4일 일',
    },
    {
      id: 4,
      categoryId: 14,
      paymentId: 2,
      title: '출력소(컬러인쇄)',
      value: 200,
      date: '7월 4일 일',
    },
    {
      id: 5,
      categoryId: 12,
      paymentId: 1,
      title: '영화 스트리밍',
      value: 9900,
      date: '7월 7일 수',
    },
    {
      id: 6,
      categoryId: 8,
      paymentId: 1,
      title: '여름 의류',
      value: 56000,
      date: '7월 7일 수',
    },
    {
      id: 7,
      categoryId: 15,
      paymentId: 2,
      title: '7월 급여',
      value: 1822480,
      date: '7월 9일 금',
    },
    {
      id: 8,
      categoryId: 4,
      paymentId: 1,
      title: '잔치국수와 김밥',
      value: 9500,
      date: '7월 9일 금',
    },
    {
      id: 9,
      categoryId: 2,
      paymentId: 1,
      title: '7월 월세',
      value: 500000,
      date: '7월 10일 토',
    },
    {
      id: 10,
      categoryId: 4,
      paymentId: 1,
      title: '두유 4개',
      value: 19140,
      date: '7월 10일 토',
    },
    {
      id: 11,
      categoryId: 14,
      paymentId: 1,
      title: '온라인 세미나 신청',
      value: 10000,
      date: '7월 13일 화',
    },
    {
      id: 12,
      categoryId: 6,
      paymentId: 1,
      title: '후불 교통비 결제',
      value: 45340,
      date: '7월 15일 목',
    },
    {
      id: 13,
      categoryId: 12,
      paymentId: 1,
      title: '스트리밍서비스 정기 결제',
      value: 10900,
      date: '7월 15일 목',
    },
  ],
};

export default data;
